name: Container build and release

on:
  workflow_dispatch:
  push:
    branches: [ "mainline" ]
    paths:
      - src/**
      - Dockerfile
      - pyproject.toml
      - uv.lock
      - .github/workflows/container-build.yml
  pull_request:
    branches: [ "mainline" ]
    paths:
      - src/**
      - Dockerfile
      - pyproject.toml
      - uv.lock
      - .github/workflows/container-build.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/layertwo/pythia-agent

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
          contents: read
          packages: write
          id-token: write
    steps:
    - uses: actions/checkout@v6

    - name: Install cosign
      if: github.event_name != 'pull_request'
      uses: sigstore/cosign-installer@v4.1.2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4.1.0

    - name: Log into registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v4.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v7.2.0
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/layertwo/pythia-agent:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Sign the published Docker image
      if: github.event_name != 'pull_request'
      env:
        TAGS: ghcr.io/layertwo/pythia-agent:latest
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
      run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
