name: Unit tests

on:
  workflow_dispatch:
  push:
    branches: [ "mainline" ]
    paths:
      - src/**
      - tests/**
      - pyproject.toml
      - uv.lock
      - .github/workflows/tests.yml
  pull_request:
    branches: [ "mainline" ]
    paths:
      - src/**
      - tests/**
      - pyproject.toml
      - uv.lock
      - .github/workflows/tests.yml

permissions:
  contents: read

jobs:

  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Install uv
      uses: astral-sh/setup-uv@v8.2.0
      with:
        version: "0.12.10"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python 3.14
      run: uv python install 3.14

    - name: Install dependencies
      run: uv sync --frozen --all-extras --all-groups

    - name: Run unit tests
      run: uv run pytest
